---
title: "Lab 2: Vacations and Vaccinations, Summer 2021"
author: 'w203: Statistics for Data Science'
date: "July 12, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

You and your team are the data scientists for the State, and are reporting to the agency head for tourism. (We like to think of the person you are reporting to as being [Mr. Mayor from Portlandia](https://youtu.be/zI6FEQKo9uE).) 

The tourism board has heard that students in the MIDS program have been working hard over the summer and could use a vacation. In this lab, you will apply what you have learned about linear regression to study vacations in the summer of 2021. 

It would be impossible to understand travel this summer without also talking about the impacts of covid-19. Travel this summer likely to be quite different from travel last summer; even travel *within* this summer might have substantial variations from month to month due to changes in policies that affect personal interactions. 

**Your task is to select and develop a research question, then conduct a regression study to analyze it.** Your research question must be specific, it should clearly state an $X$ and a $Y$ variable. For this, you will have to use the skills you have developed in RDADA to work on a question that can be addressed using a modeling approach. It is not enough to say "we are examining how policies affect tourism", or "we are examining how covid has affected tourism". These types of questions are not amenable to a modeling based approach and would likely generate a fishing expedition. Instead, you and the team will have to use your understanding of, intuition about, and data from the world to propose a question and generate an answer. 

Once you have a measurement goal, you will build a set of linear models that are tailored to that goal, and will present them to your readers in a manner that allows the reader to learn as much as possible. This might be a well formatted regression table or a series of tables and charts. 

## Example of a Research Question 
Suppose that your team is interested in craft-beer tourism, *big-business* in parts of the United States. A starting place for your investigation might be collecting information and data about the industry over the past several years, then inductively examining the impacts of both covid-19 and master's degree enrollment on beer-tourism. Analysis at this level is not specific enough to be generate a model; your team will have to continue to refine your focus to propose a specific question. 

After coming to understand the landscape, you and your team might propose to examine the effects of subsidies that reduce the cost of rent for craft-breweries. But, even this is not specific enough: What outcomes are under consideration? 

The team might reason that such subsidies should increase the number of breweries in operation; or, the number of barrels of craft-beer brewed within the subsidized geography; or, should  increase the number of vacation rentals and carshare rides in the area of the subsidies. Each of these outcomes might be affected by increased brewing activity, but a useful research question should be well-enough developed to identify an outcome at this level. And so, the group might elect to focus their primary attention on one outcome for this report: **"How do subsidies that reduce the cost of rent for craft-brewerires affect the occupancy rate of8 vacation rentals in the vicinity of breweries?"**

## A Group Assignment

**This is a group assignment.** Your live session instructor will coordinate the formation of groups. We would like to encourage teams to focus on using the lab as a way to learn how to work as a team of collaborating data scientists on shared code; how to clean and organize data; and, how to present work in a compelling way. As a result, we encourage teams to allow individuals to take risks and be supportive in the face of successes and failures. Create an opportunity for people who want to improve a particular skill to do so -- this might be project coordination, management of code through git, plotting, or any of the many aspects that you'll work on. *We hope that you can support and learn from one another through this team-based project.* 

# Deliverables 

| Deliverable Name       | Week Due | Grade Weight |
|------------------------|----------|--------------| 
| [Research Proposal]    | Week 12  | 10%          | 
| [Within-Team Review]   | Week 12  | 5%           | 
| [Final Presentation]   | Week 14  | 10%          | 
| [Final Report]         | Week 14  | 75%          | 


# Data

You are not required to use any specific data source; nor are you prohibited from using any specific data source. You are allowed to add extra variables from other sources, but for each additional data source, the team will have to document and cite the source.

Because of the limitations of models we have studied in the course, we recommend that data for analysis be aggregated to either the state- or county-level. 

In w203 we have not dealt with *time* in any way. While your descriptive analysis might show plots of outcomes that vary over time, models that have repeated observations through time should likely be avoided. (If the team can marshal time-series models, they are not prohibited from doing so, but these tools are beyond the scope of the course.) 

As a starting place, your team might consider these data sources.

- [The American Community Survey](https://data.census.gov/cedsci/table?q=ACS&g=0100000US.04000.001&tid=ACSDP1Y2019.DP05&moe=false&hidePreview=true) This product from the US Census Bureau contains state-level demographics and other indicators of general interest.
- [Airbnb Booking Data](http://insideairbnb.com/get-the-data.html) This data is not published by Airbnb; rather, it is scraped and posted by an [advocacy group](http://insideairbnb.com/about.html). (The group seems to advocate for the reduction in Airbnb short-term rentals; knowing this motivation can help you to evaluate the source of the data.) 
- [CDC Data on Vaccinations](https://data.cdc.gov/Vaccinations/COVID-19-Vaccinations-in-the-United-States-County/8xkx-amqh) This data product from the US Centers for Disease Control contains county-level information about vaccination rates. More description of this data is available [here](https://covid.cdc.gov/covid-data-tracker/#vaccinations-county-view).
- [COVID-19 US State Policy Database](www.tinyurl.com/statepolicies) A database of state policy responses to the pandemic, compiled by researchers at the Boston University School of Public Health.
- [New York Times Covid-19 Data](https://github.com/nytimes/covid-19-data) A database, compiled from several authoritative sources on the occurrence of covid-19 at the county level.  
- [Bureau of Transportation Statistics](https://data.bts.gov/Research-and-Statistics/Trips-by-Distance/w96p-f2qv) A dataset with the number of trips of a given distance (i.e. 1-3 miles; 250-500 miles) taken by residents of a specified geography (i.e. a county)  
- [COVID-19 Community Mobility Report](https://www.google.com/covid19/mobility/) A dataset collected by Google that includes state-level measurements of individual mobility, by categeory (e.g. supermarkets, parks and recreation).
- [NORC Covid Impact Survey](https://www.covid-impact.org/project-overview) In June 2020, the National Opinion Research Council surveyed US residents and asked about their lives during the Pandemic.

# Final Project Components {.tabset}

## Research Proposal

After a week of work, the project team will produce a one page research-proposal that defines the teams' research question, data sources and plan of action. 

The research question should be informed by an understanding of the datasets that are available, and the information that is available in those data sets. This means that the the team will need to have done at least preliminary work understand what data is available. A motivated team might form their research question, and begin to build a functioning data pipeline as an investment in ongoing project success. 

The research proposal is intended to provide a structure for the team to have early conversations; it will be graded credit/no credit for completeness (i.e. a reasonable effort by the team will receive full marks). Your instructor will read these proposals, and if any course corrections are necessary, will contact the team. 

**This proposal is due in week 12, and needs only one submission per team.**

## Within-Team Review

Being an effective, supportive team member is a crucial part of data science work. Your performance on this lab includes the role you play in supporting your teammates. This includes being responsive, creating an environment in which all members feel included, and above all treating each other with respect. In line with this perspective, we will ask each team member to write to two paragraphs to their instructor about the progress they have made individually, and the team has made as a whole toward completing their report. 

This self-assessment should: 

- Reflect on the strengths and weaknesses of the team and the team's process to this point in the project. 
   - Where your collaboration has worked well, how will you work to ensure that these successful practices continue to be employed? 
   - If there are places where collaboration has been challenging, what can the team do jointly to improve? 
- If there are any individual performances that deserve special recognition, please let your instructor know in this evaluation.
- If there are any individual performances that require special attention, please also let your instructor know in this evaluation. 

Instructors ill treat these reviews as confidential and will not take any action without first consulting you.

**This reflection is due in week 12, an requires one submission per person.** You will submit this through Gradescope, and like all parts of your educational record, this will be treated confidentially by the instructional team. 

## Final Presentation 

During the Unit 14 live session, each team will give a slide presentation of their work to their classmates -- i.e. collaborating data scientists. Your classmates they will need to be informed of the specific research question that you are addressing.  **The presentation should be structured as 10 minutes of presentation and 5 minutes of questions from our classmates.** We'd like to note that this is an *incredibly* limited amount of time to present. The materials that you present should reflect these serious constraints! 

1. There should be no more than two slides that set-up your research question and these slides should take no more than two minutes to present. On this slide, it is quite alright to state bluntly: "**Research Question**: Do subsidies on rental-income for craft beer breweries cause increases in brewing output and localized economic activity?" (2 minutes)
2. There should be at least one, and not more than two, slides that describe the variables that you're using in your models. These slides should cover the important features of the variables that you're using: how are they are measured, the unit of observation, plots of how these variables are distributed, and why this *particular* variable appropriate to use to answer your research question. (3 minutes) 
   - Do not present R code, discuss data wrangling, or normality - details like this are best left to the full analysis. 

3. There should then be several slides that provide what you've learned from your models. If you show model results, you need to provide your audience with enough time to read and engage with these models; not flash past them. Any model you show will take at least one minute to talk about. 

Finally, a few more general thoughts: 

- Practice your talk with a timer!
- If you divide your talk with your teammates, practice your section with a timer so that you do not spill over into your teammates' time.

## Final Report

Your final deliverable is a written statistical analysis documenting your findings. **Please limit your submission to 8000 words, excluding code cells and R output.**

The exact format of your report is flexible, but it should include the following elements.

### 1. An Introduction

Your introduction should present a research question and explain the concept that you're attempting to measure and how it will be operationalized. This section should pave the way for the body of the report, preparing the reader to understand why the models are constructed the way that they are. It is not enough to simply say "We are looking for policies that help against COVID"  Your introduction must do work for you, focusing the reader on a specific measurement goal, making them care about it, and propelling the narrative forward. This is also good time to put your work into context, discuss cross-cutting issues, and assess the overall appropriateness of the data.

### 2. A Model Building Process

You will next build a set of models to investigate your research question, documenting your decisions. Here are some things to keep in mind during your model building process:

1. *What do you want to measure*? Make sure you identify one, or a few, variables that will allow you to derive conclusions relevant to your research question, and include those variables in all model specifications. How are the variables that you will be modeling distributed? Provide enough context and information about your data for your audience to understand whatever model results you will eventually present. 
2. Is your modeling goal one of description or explanation? 
3. What [covariates](https://en.wikipedia.org/wiki/Dependent_and_independent_variables#Statistics_synonyms) help you achieve your modeling goals? What covariates are problematic, either due to *collinearity*, or because they will absorb some of a causal effect you want to measure?
4. What *transformations*, if any, should you apply to each variable? These transformations might reveal linearities in the data, make our results relevant, or help us meet model assumptions.
5. Are your choices supported by exploratory data analysis (*EDA*)? You will likely start with some general EDA to *detect anomalies* (missing values, top-coded variables, etc.). From then on, your EDA should be interspersed with your model building. Use visual tools to *guide* your decisions. You can also leverage statistical *tests* to help assess whether variables, or groups of variables, are improving model fit.

At the same time, it is important to remember that you are not trying to create one perfect model. You will create several specifications, giving the reader a sense of how robust (or sensitive) your results are to modeling choices, and to show that you're not just cherry-picking the specification that leads to the largest effects.

At a minimum, you should include the following three specifications:

1. **Limited Model**: The first model you include should include *only the key variables* you want to measure. These variables might be transformed, as determined by your EDA, but the model should include the absolute minimum number of covariates (perhaps one, or at most two-three, covariates if they are so crucial that it would be unreasonable to omit them). 
1. **Model Two**: One model that includes *key explanatory variables and covariates that you believe advance your modeling* goals without introducing too much multicollinearity or causing other issues of confounding. This model should strike a balance between accuracy and parsimony and reflect your best understanding of the relationships among key variables.
1. **Model Three**: One model that includes the *previous covariates, and many other covariates*, erring on the side of inclusion. A key purpose of this model is to evaluate how parameters of interest change (if at all) when additional, potentially colinear variables are included in the model specification.

You goal with producing these models is to choose models that encircle the space of reasonable modeling choices, and to give an overall understanding of how these choices impact results.

### 3. A Regression Table

You should display all of your model specifications in a regression table, using a package like [`stargazer`](https://cran.r-project.org/web/packages/stargazer/vignettes/stargazer.pdf) to format your output. It should be easy for the reader to find the coefficients that represent key effects near the top of the regression table, and scan horizontally to see how they change from specification to specification. Make sure that you display the most appropriate standard errors in your table.

In your text, comment on both *statistical significance and practical significance*. You may want to include statistical tests besides the standard t-tests for regression coefficients. 

### 4. Limitations of your Model 

As a team, evaluate all of the CLM assumptions that must hold for your model. However, do not report an exhaustive examination all 5 CLM assumptions in the main report. Instead, bring forward only those assumptions that you or your reader might think pose significant problems for your analysis. For each problem that you identify, describe the statistical consequences. If you are able to identify any strategies to mitigate the consequences, explain these strategies. 

Note that you may need to change your model specifications in response to violations of the CLM. 

### 5. Discussion of Omitted Variables

If the team has taken up an explanatory (i.e. causal) question to evaluate, then identify what you think are the most important *omitted variables* that bias results you care about. For each variable you name, you should *reason about the direction of bias* caused by omitting this variable. If you can argue whether the bias is large or small, that is even better. State whether you have any variables available that may proxy (even imperfectly) for the omitted variable. Pay particular attention to whether each omitted variable bias is *towards zero or away from zero*. You will use this information to judge whether the effects you find are likely to be real, or whether they might be entirely an artifact of omitted variable bias.

### 6. Conclusion

Make sure that you end your report with a discussion that distills key insights from your estimates and addresses your research question. 

# Encouragment for the Project

This project touches on many of the skills that you have developed in the course. 

- When you are reasoning about the world and the way that it works, you are implicitly reasoning about *random variables*. Although you might not reason with specific functions (e.g. $f_{x} = x^2$) to describe these random variables, you are very likely to be reasoning about conditional expectations. In the example of craft-beer brewing from above, the question that the hypothetical team has proposed is one of how the expected value of beer production changes as a result of changes in policy inputs. 
- This class is not a class in pure theory! And so, theories you have about the world need to be informed by samples of data. These samples might be iid, or they might not be. The team will have to assess how this, and other possible violations of model assumptions shape what they learn. 
- Given a set of input variables, OLS regression produces an estimate of the BLP. But, how good of a predictor is this predictor? And, does the team have enough data to rely on large-sample theory, or does the team need to engage with the requirements of the smaller-sample? 
- Throughout, you will have to communicate both to a technical and non-technical audience. 

**Finally, have fun with this project.** You have worked hard this semester to build a foundation for reasoning about the world through statistical models. This project is a chance for you and a team of peers to work to apply this reasoning.